name: Feature request
about: Suggest an idea for this project
title: '[Feature Request]: '
labels: '[feature]'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using XREngine! What feature would you like to see added?
  - type: input
    id: description
    attributes:
      label: Feature Description
      description: Is your feature request related to a problem? Please describe it clearly.
    validations:
      required: true